### PR TITLE
Update en_us.cfg

### PR DESCRIPTION
**Pull request by Baparrs**
Added missing tags and expanded existing tags for all parts

### CODE REVIEW

**Comment by linuxgurugamer** [comment]
Umm, did you forget to include the cfg files in which you added tags when there werent any before?

**Comment by linuxgurugamer** [comment]
If you weren't/aren't going to update the cfg files, that's fine, just let me know.
Thanks

**Comment by Baparrs** [comment]
Doh! Sorry - lots of other stuff on my mind - I'll get those out.

**Comment by linuxgurugamer** [comment]
Not a problem, I'll wait.  Just post another message here when you have pushed up the changes.
Thanks

**Comment by Baparrs** [comment]
Tags in the cfg files have been added

**Pull request merged**
